version: "3.7"

services:
    postgres:
        init: true
        build: "."
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "data_postgres:/var/lib/postgresql/data"
            - "./..:/workspace"
        ports:
            - "3000:3000"
            - "8000:8000"
            - "5432:5432"
        environment:
            - "POSTGRES_PASSWORD=me"
            - "PG_CONNECTION_STRING=postgresql://postgres:me@localhost:5432/postgres"
            
volumes:
    data_postgres:
